IGNORE_SPELL_AMP_KV = {
	["omniknight_hammer_of_purity"] = {["bonus_damage"] = true},
	["jakiro_liquid_fire"] = {["pct_health_damage"] = true},
	["jakiro_liquid_ice"] = {["pct_health_damage"] = true},
	["sandking_caustic_finale"] = {["caustic_finale_damage_pct"] = true},
	["morphling_adaptive_strike_agi"] = {["damage_min"] = true,["damage_max"] = true},
	["bloodseeker_rupture"] = {["hp_pct"] = true},
	["abyssal_underlord_firestorm"] = {["burn_damage"] = true},
	["phoenix_sun_ray"] = {["hp_perc_damage"] = true},
	["venomancer_poison_nova"] = {["damage"] = true},
	["warlock_fatal_bonds"] = {["damage_share_percentage"] = true},
	["enigma_midnight_pulse"] = {["damage_percent"] = true},
	["enigma_black_hole"] = {["scepter_pct_damage"] = true},
	["obsidian_destroyer_arcane_orb"] = {["mana_pool_damage_pct"] = true},
	["phantom_assassin_fan_of_knives"] = {["pct_health_damage_initial"] = true,["pct_health_damage"] = true},
	["huskar_life_break"] = {["health_cost_percent"] = true,["health_damage"] = true},
	["item_orchid"] = {["silence_damage_percent"] = true},
	["item_bloodthorn"] = {["silence_damage_percent"] = true},
	["item_bloodthorn_2"] = {["silence_damage_percent"] = true},
	["item_bloodthorn_3"] = {["silence_damage_percent"] = true},
	["item_bloodthorn_4"] = {["silence_damage_percent"] = true},
	["item_bloodthorn_5"] = {["silence_damage_percent"] = true},
	["kez_raptor_dance"] = {["katana_bleed_attack_damage_pct"] = true},
	["kez_kazurai_katana"] = {["max_health_damage_pct"] = true},
	["venomancer_noxious_plague"] = {["damage_per_second"] = true},
	-- ["elder_titan_earth_splitter"] = {["damage_pct"] = true},
	-- ["mod_elder_titan_earth_splitter"] = {["damage_pct"] = true},
	["batrider_sticky_napalm"] = {["damage"] = true},
}

-- spell_name = spell_amp_reduction (100 for no spell amp) 
-- (only use this when you want the skill/item to be completely useless with spell amp,  it will even go negative if the spell amp is higher than the reduction)
IGNORE_SPELL_AMP_FILTER = {
	["lina_combustion"] = 100,
	["lina_slow_burn"] = 100,
	["item_revenant_ebf"] = 90,
	["item_revenant_ebf_2"] = 85,
	["item_revenant_ebf_3"] = 80,
	["item_revenant_ebf_4"] = 75,
	["item_revenant_ebf_5"] = 70,
	["bloodseeker_blood_mist_codex"] = 100,
	["bloodseeker_bloodrage"] = 100,
	["primal_beast_trample"] = 80,
	["imba_enigma_black_hole"] = 50,
	["imba_enigma_midnight_pulse"] = 50,
	["muerta_pierce_the_veil"] = 50,
	["huskar_burning_spear"] = 100,
	["winter_wyvern_arctic_burn"] = 100,
	["elder_titan_earth_splitter"] = 30,
	["necrolyte_heartstopper_aura"] = 60,
	["shadow_demon_disseminate"] = 100,
	["shadow_demon_demonic_purge"] = 100,
	["item_devastator"] = 100,
	["item_devastator_2"] = 100,
	["item_devastator_3"] = 100,
	["item_devastator_4"] = 100,
	["item_devastator_5"] = 100,
	["drow_ranger_multishot"] = 100,
	["kez_raptor_dance"] = 100,
	["zuus_static_field"] = 80,
	["kez_kazurai_katana"] = 90,
	["omniknight_hammer_of_purity"] = 100,
	["viper_poison_attack"] = 75,
	["item_jidi_pollen_bag"] = 100,
	["leshrac_diabolic_edict"] = 50,
}

IGNORE_SPELL_AMP_FILTER_HERO = {
	-- ["npc_dota_hero_phantom_assassin"] = 0.25,
	["npc_dota_hero_riki"] = 0.9,
	["npc_dota_hero_silencer"] = 0.6,
	["npc_dota_hero_alchemist"] = 0.7
}

hero_keys = {
	"npc_dota_hero_mars",
	"npc_dota_hero_largo",
	"npc_dota_hero_nevermore",
	"npc_dota_hero_phantom_assassin",
	"npc_dota_hero_spectre",
	"npc_dota_hero_templar_assassin",
	"npc_dota_hero_snapfire",
	"npc_dota_hero_antimage",
	"npc_dota_hero_arc_warden",
	"npc_dota_hero_bloodseeker",
	"npc_dota_hero_bounty_hunter",
	"npc_dota_hero_clinkz",
	"npc_dota_hero_drow_ranger",
	"npc_dota_hero_faceless_void",
	"npc_dota_hero_ember_spirit",
	"npc_dota_hero_gyrocopter",
	"npc_dota_hero_luna",
	"npc_dota_hero_medusa",
	"npc_dota_hero_sniper",
	"npc_dota_hero_lina",
	"npc_dota_hero_omniknight",
	"npc_dota_hero_axe",
	"npc_dota_hero_tidehunter",
	"npc_dota_hero_tusk",
	"npc_dota_hero_sven",
	"npc_dota_hero_kunkka",
	"npc_dota_hero_alchemist",
	"npc_dota_hero_bristleback",
	"npc_dota_hero_centaur",
	"npc_dota_hero_chaos_knight",
	"npc_dota_hero_doom",
	"npc_dota_hero_dragon_knight",
	"npc_dota_hero_earthshaker",
	"npc_dota_hero_huskar",
	"npc_dota_hero_legion_commander",
	"npc_dota_hero_night_stalker",
	"npc_dota_hero_tinker",
	"npc_dota_hero_pangolier",
	"npc_dota_hero_invoker",
	"npc_dota_hero_doom_bringer",
	"npc_dota_hero_life_stealer",
	"npc_dota_hero_ogre_magi",
	"npc_dota_hero_primal_beast",
	"npc_dota_hero_pudge",
	"npc_dota_hero_slardar",
	"npc_dota_hero_spirit_breaker",
	"npc_dota_hero_shredder",
	"npc_dota_hero_tiny",
	"npc_dota_hero_treant",
	"npc_dota_hero_abyssal_underlord",
	"npc_dota_hero_earth_spirit",
	"npc_dota_hero_elder_titan",
	"npc_dota_hero_skeleton_king",
	"npc_dota_hero_undying",
	"npc_dota_hero_dawnbreaker",
	"npc_dota_hero_juggernaut",
	"npc_dota_hero_wisp",
	"npc_dota_hero_abaddon",
	"npc_dota_hero_bane",
	"npc_dota_hero_batrider",
	"npc_dota_hero_beastmaster",
	"npc_dota_hero_brewmaster",
	"npc_dota_hero_broodmother",
	"npc_dota_hero_chen",
	"npc_dota_hero_rattletrap",
	"npc_dota_hero_dark_willow",
	"npc_dota_hero_dazzle",
	"npc_dota_hero_lone_druid",
	"npc_dota_hero_enigma",
	"npc_dota_hero_lycan",
	"npc_dota_hero_magnataur",
	"npc_dota_hero_mirana",
	"npc_dota_hero_marci",
	"npc_dota_hero_phoenix",
	"npc_dota_hero_sand_king",
	"npc_dota_hero_vengefulspirit",
	"npc_dota_hero_venomancer",
	"npc_dota_hero_techies",
	"npc_dota_hero_void_spirit",
	"npc_dota_hero_windrunner",
	"npc_dota_hero_winter_wyvern",
	"npc_dota_hero_visage",
	"npc_dota_hero_nyx_assassin",
	"npc_dota_hero_ancient_apparition",
	"npc_dota_hero_crystal_maiden",
	"npc_dota_hero_death_prophet",
	"npc_dota_hero_disruptor",
	"npc_dota_hero_grimstroke",
	"npc_dota_hero_jakiro",
	"npc_dota_hero_keeper_of_the_light",
	"npc_dota_hero_leshrac",
	"npc_dota_hero_lich",
	"npc_dota_hero_lion",
	"npc_dota_hero_muerta",
	"npc_dota_hero_furion",
	"npc_dota_hero_necrolyte",
	"npc_dota_hero_oracle",
	"npc_dota_hero_obsidian_destroyer",
	"npc_dota_hero_puck",
	"npc_dota_hero_queenofpain",
	"npc_dota_hero_pugna",
	"npc_dota_hero_ringmaster",
	"npc_dota_hero_rubick",
	"npc_dota_hero_shadow_shaman",
	"npc_dota_hero_silencer",
	"npc_dota_hero_skywrath_mage",
	"npc_dota_hero_storm_spirit",
	"npc_dota_hero_warlock",
	"npc_dota_hero_enchantress",
	"npc_dota_hero_hoodwink",
	"npc_dota_hero_kez",
	"npc_dota_hero_monkey_king",
	"npc_dota_hero_morphling",
	"npc_dota_hero_naga_siren",
	"npc_dota_hero_phantom_lancer",
	"npc_dota_hero_razor",
	"npc_dota_hero_riki",
	"npc_dota_hero_slark",
	"npc_dota_hero_troll_warlord",
	"npc_dota_hero_ursa",
	"npc_dota_hero_terrorblade",
	"npc_dota_hero_viper",
	"npc_dota_hero_weaver",
	"npc_dota_hero_witch_doctor",
	"npc_dota_hero_shadow_demon",
	'npc_dota_hero_zuus'
}