SPECIAL_UPGRADES = SPECIAL_UPGRADES or {}

SPECIAL_UPGRADES.data = {
	echo_cast = {
		upgrade_name = "echo_cast",
		ability_name = "special_upgrade_echo_cast",
		modifier_name = "modifier_special_upgrade_echo_cast",
		description = "#special_upgrade_echo_cast",
		value = 12,
		value_text = "12%",
		special_value_name = "echo_chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			echo_chance = 12,
		},
		excluded_behaviors = {
			DOTA_ABILITY_BEHAVIOR_PASSIVE = true,
			DOTA_ABILITY_BEHAVIOR_TOGGLE = true,
			DOTA_ABILITY_BEHAVIOR_AUTOCAST = true,
		},
	},
	arcane_surge = {
		upgrade_name = "arcane_surge",
		ability_name = "special_upgrade_arcane_surge",
		modifier_name = "modifier_special_upgrade_arcane_surge",
		description = "#special_upgrade_arcane_surge",
		value = 35,
		value_text = "+35%",
		special_value_name = "spell_amp",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			spell_amp = 35,
			duration = 4,
		},
		excluded_behaviors = {
			DOTA_ABILITY_BEHAVIOR_PASSIVE = true,
			DOTA_ABILITY_BEHAVIOR_TOGGLE = true,
			DOTA_ABILITY_BEHAVIOR_AUTOCAST = true,
		},
	},
	spell_lifesteal = {
		upgrade_name = "spell_lifesteal",
		ability_name = "special_upgrade_spell_lifesteal",
		modifier_name = "modifier_special_upgrade_spell_lifesteal",
		description = "#special_upgrade_spell_lifesteal",
		value = 8,
		value_text = "8%",
		special_value_name = "lifesteal_pct",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			lifesteal_pct = 8,
		},
		excluded_behaviors = {
			DOTA_ABILITY_BEHAVIOR_PASSIVE = true,
			DOTA_ABILITY_BEHAVIOR_TOGGLE = true,
			DOTA_ABILITY_BEHAVIOR_AUTOCAST = true,
		},
	},
	omnislash_cd = {
		upgrade_name = "omnislash_cd",
		ability_name = "special_upgrade_omnislash_cd",
		modifier_name = "modifier_special_upgrade_omnislash_cd",
		description = "#special_upgrade_omnislash_cd",
		value = 1,
		value_text = "1s",
		special_value_name = "cooldown_reduction",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			cooldown_reduction = 1,
		},
		target_abilities = {
			juggernaut_omni_slash = true,
		},
	},
	gods_strength_cd = {
		upgrade_name = "gods_strength_cd",
		ability_name = "special_upgrade_gods_strength_cd",
		modifier_name = "modifier_special_upgrade_gods_strength_cd",
		description = "#special_upgrade_gods_strength_cd",
		value = 1,
		value_text = "1s",
		special_value_name = "cooldown_reduction",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			cooldown_reduction = 1,
		},
		target_abilities = {
			sven_gods_strength = true,
		},
	},
	echo_slam = {
		upgrade_name = "echo_slam",
		ability_name = "special_upgrade_echo_slam",
		modifier_name = "modifier_special_upgrade_echo_slam",
		description = "#special_upgrade_echo_slam",
		value = 10,
		value_text = "10",
		special_value_name = "attacks",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			attacks = 10,
		},
		target_abilities = {
			earthshaker_aftershock = true,
		},
	},
	thunder_strike_chance = {
		upgrade_name = "thunder_strike_chance",
		ability_name = "special_upgrade_thunder_strike_chance",
		modifier_name = "modifier_special_upgrade_thunder_strike_chance",
		description = "#special_upgrade_thunder_strike_chance",
		value = 35,
		value_text = "35%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			chance = 35,
		},
		target_abilities = {
			disruptor_thunder_strike = true,
		},
	},
	counter_helix_call = {
		upgrade_name = "counter_helix_call",
		ability_name = "special_upgrade_counter_helix_call",
		modifier_name = "modifier_special_upgrade_counter_helix_call",
		description = "#special_upgrade_counter_helix_call",
		value = 100,
		value_text = "100%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			chance = 100,
		},
		target_abilities = {
			axe_berserkers_call = true,
		},
	},
	mystic_snake_mana = {
		upgrade_name = "mystic_snake_mana",
		ability_name = "special_upgrade_mystic_snake_mana",
		modifier_name = "modifier_special_upgrade_mystic_snake_mana",
		description = "#special_upgrade_mystic_snake_mana",
		value = 10,
		value_text = "10s",
		special_value_name = "cooldown",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			cooldown = 10,
			max_snakes = 2,
		},
		target_abilities = {
			medusa_mystic_snake = true,
		},
	},
	multishot_chance = {
		upgrade_name = "multishot_chance",
		ability_name = "special_upgrade_multishot_chance",
		modifier_name = "modifier_special_upgrade_multishot_chance",
		description = "#special_upgrade_multishot_chance",
		value = 35,
		value_text = "35%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			chance = 35,
			wave_count = 1,
		},
		target_abilities = {
			drow_ranger_multishot = true,
		},
	},
	cookie_mortimer_kiss = {
		upgrade_name = "cookie_mortimer_kiss",
		ability_name = "special_upgrade_cookie_mortimer_kiss",
		modifier_name = "modifier_special_upgrade_cookie_mortimer_kiss",
		description = "#special_upgrade_cookie_mortimer_kiss",
		value = 3,
		value_text = "3s",
		special_value_name = "duration",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		values = {
			duration = 3,
		},
		target_abilities = {
			snapfire_scatterblast = true,
		},
	},
}

local function AddDarkmoonUpgrade(upgrade)
	SPECIAL_UPGRADES.data[upgrade.upgrade_name] = upgrade
end

local DARKMOON_SPECIAL_UPGRADE_PORTS = {
	{
		upgrade_name = "enchantress_impetus_doubled",
		ability_name = "special_upgrade_enchantress_impetus_doubled",
		modifier_name = "modifier_enchantress_impetus_doubled_upgrade",
		description = "#special_upgrade_enchantress_impetus_doubled",
		value = 22,
		value_text = "22%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "impetused",
		values = { chance = 22, extra_attacks = 3 },
		target_abilities = { enchantress_impetus = true },
		extra_modifiers = { "modifier_enchantress_impetus_doubled", "modifier_enchantress_impetus_no_mana" },
	},
	{
		upgrade_name = "enchantress_impetus_no_mana",
		ability_name = "special_upgrade_enchantress_impetus_no_mana",
		modifier_name = "modifier_enchantress_impetus_no_mana",
		description = "#special_upgrade_enchantress_impetus_no_mana",
		value = 100,
		value_text = "Free",
		special_value_name = "mana_reduction",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "no_mana",
		values = { mana_reduction = 100 },
		target_abilities = { enchantress_impetus = true },
	},
	{
		upgrade_name = "sniper_assassinate_chance",
		ability_name = "special_upgrade_sniper_assassinate_chance",
		modifier_name = "modifier_sniper_assissinate_chance_dark_moon",
		description = "#special_upgrade_sniper_assassinate_chance",
		value = 11,
		value_text = "11%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "assassinated",
		values = { chance = 11 },
		target_abilities = { sniper_assassinate = true, sniper_assassinate_sb_2023 = true },
	},
	{
		upgrade_name = "bristleback_quilled",
		ability_name = "special_upgrade_bristleback_quilled",
		modifier_name = "modifier_bristleback_quilled_dark_moon",
		description = "#special_upgrade_bristleback_quilled",
		value = 15,
		value_text = "15%",
		special_value_name = "hp_threshold",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "quilled",
		values = { hpMargines = 0.15, hpRegen = 0.1, duration = 5.1, interval = 0.5, coolDown = 45 },
		target_abilities = { bristleback_quill_spray = true },
		extra_modifiers = { "modifier_bristleback_quilled_metamorph_dark_moon" },
	},
	{
		upgrade_name = "faceless_void_small_chrono",
		ability_name = "special_upgrade_faceless_void_small_chrono",
		modifier_name = "modifier_faceless_void_small_chrono_dark_moon",
		description = "#special_upgrade_faceless_void_small_chrono",
		value = 200,
		value_text = "200",
		special_value_name = "radius",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "sphered",
		values = { radius = 200, duration = 1.75 },
		target_abilities = { faceless_void_time_walk = true },
	},
	{
		upgrade_name = "lina_laguna_debuff",
		ability_name = "special_upgrade_lina_laguna_debuff",
		modifier_name = "modifier_lina_laguna_blade_effect_dark_moon",
		description = "#special_upgrade_lina_laguna_debuff",
		value = 50,
		value_text = "+50%",
		special_value_name = "damage_amp",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "enemy_weak",
		values = { duration = 3, dmg = 50, miss = 75, miss_arround = 45, radius = 300 },
		target_abilities = { lina_laguna_blade = true },
		extra_modifiers = { "modifier_lina_laguna_debuff_dark_moon" },
	},
	{
		upgrade_name = "lina_dragon_slave_lsa",
		ability_name = "special_upgrade_lina_dragon_slave_lsa",
		modifier_name = "modifier_lina_light_strike_array_slave_upgrade",
		description = "#special_upgrade_lina_dragon_slave_lsa",
		value = 2,
		value_text = "2",
		special_value_name = "extra_strikes",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "strike_slave",
		values = { extra_strikes = 2 },
		target_abilities = { lina_dragon_slave = true },
	},
	{
		upgrade_name = "lina_lsa_line",
		ability_name = "special_upgrade_lina_lsa_line",
		modifier_name = "modifier_lina_light_strike_array_line_upgrade_sb_2023",
		description = "#special_upgrade_lina_lsa_line",
		value = 1,
		value_text = "Line",
		special_value_name = "line_strikes",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "line_strikes",
		values = { line_strikes = 1 },
		target_abilities = { lina_light_strike_array = true },
	},
	{
		upgrade_name = "drow_frost_freeze",
		ability_name = "special_upgrade_drow_frost_freeze",
		modifier_name = "modifier_drow_ranger_frost_arrow_freez_dark_moon",
		description = "#special_upgrade_drow_frost_freeze",
		value = 3,
		value_text = "3s",
		special_value_name = "interval",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "frozen",
		values = { stun = 1, interval = 3 },
		target_abilities = { drow_ranger_frost_arrows = true },
		extra_modifiers = { "modifier_drow_ranger_frost_arrow_freez_debuff_dark_moon" },
	},
	{
		upgrade_name = "witch_doctor_cask_ward",
		ability_name = "special_upgrade_witch_doctor_cask_ward",
		modifier_name = "modifier_witch_doctor_paralyzing_cask_dark_moon",
		description = "#special_upgrade_witch_doctor_cask_ward",
		value = 5,
		value_text = "5",
		special_value_name = "bounces",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "freeward",
		values = { bounces = 5, maxAttacks = 2, wardDuration = 4.5, damage = 100 },
		target_abilities = { witch_doctor_paralyzing_cask = true },
	},
	{
		upgrade_name = "witch_doctor_maledict_attack",
		ability_name = "special_upgrade_witch_doctor_maledict_attack",
		modifier_name = "modifier_witch_doctor_maledict_attack_sb_2023",
		description = "#special_upgrade_witch_doctor_maledict_attack",
		value = 1,
		value_text = "Attack",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "maledict_attack",
		values = { enabled = 1 },
		target_abilities = { witch_doctor_maledict = true },
	},
	{
		upgrade_name = "lion_mana_drain_hex",
		ability_name = "special_upgrade_lion_mana_drain_hex",
		modifier_name = "modifier_lion_mana_hex_around_dark_moon",
		description = "#special_upgrade_lion_mana_drain_hex",
		value = 750,
		value_text = "750",
		special_value_name = "range",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "hexed",
		values = { range = 750, multiplier = 0.5 },
		target_abilities = { lion_mana_drain = true },
	},
	{
		upgrade_name = "pangolier_revolver",
		ability_name = "special_upgrade_pangolier_revolver",
		modifier_name = "modifier_pangolier_revolver_dark_moon",
		description = "#special_upgrade_pangolier_revolver",
		value = 75,
		value_text = "75%",
		special_value_name = "damage",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "revolver",
		values = { damage = 75 },
		target_abilities = { pangolier_swashbuckle = true },
	},
	{
		upgrade_name = "lone_druid_little_bear",
		ability_name = "special_upgrade_lone_druid_little_bear",
		modifier_name = "modifier_lone_druid_little_bear_dark_moon",
		description = "#special_upgrade_lone_druid_little_bear",
		value = 1,
		value_text = "Bear",
		special_value_name = "bear_count",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "little_bear",
		values = { bear_count = 1 },
		target_abilities = { lone_druid_spirit_bear = true },
	},
	{
		upgrade_name = "pudge_dismember_hooks",
		ability_name = "special_upgrade_pudge_dismember_hooks",
		modifier_name = "modifier_pudge_dismember_hooks_upgrade",
		description = "#special_upgrade_pudge_dismember_hooks",
		value = 1,
		value_text = "Hooks",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "pudge_dismember_hooks",
		values = { enabled = 1 },
		target_abilities = { pudge_dismember = true },
	},
	{
		upgrade_name = "bane_fiends_grip_brain_sap",
		ability_name = "special_upgrade_bane_fiends_grip_brain_sap",
		modifier_name = "modifier_fiends_grip_nightmare_hunger_upgrade",
		description = "#special_upgrade_bane_fiends_grip_brain_sap",
		value = 1,
		value_text = "1s",
		special_value_name = "interval",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "nightmare_hungry",
		values = { interval = 1 },
		target_abilities = { bane_fiends_grip = true },
	},
	{
		upgrade_name = "dragon_knight_breathe_attack",
		ability_name = "special_upgrade_dragon_knight_breathe_attack",
		modifier_name = "modifier_dk_breathe_fire_extra_attack_upgrade",
		description = "#special_upgrade_dragon_knight_breathe_attack",
		value = 18,
		value_text = "18%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "fire_attack",
		values = { chance = 18 },
		target_abilities = { dragon_knight_breathe_fire = true },
	},
	{
		upgrade_name = "dawnbreaker_hammer_counter",
		ability_name = "special_upgrade_dawnbreaker_hammer_counter",
		modifier_name = "modifier_db_hammer_attack_chance_upgrade",
		description = "#special_upgrade_dawnbreaker_hammer_counter",
		value = 12,
		value_text = "12%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "solar_hammers",
		values = { chance = 12, cooldown = 1.75 },
		target_abilities = { dawnbreaker_celestial_hammer = true },
	},
	{
		upgrade_name = "windrunner_powershot_attack",
		ability_name = "special_upgrade_windrunner_powershot_attack",
		modifier_name = "modifier_windrunner_attack_powershot_upgrade",
		description = "#special_upgrade_windrunner_powershot_attack",
		value = 20,
		value_text = "20%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "attack_shot",
		values = { chance = 20 },
		target_abilities = { windrunner_powershot = true },
	},
	{
		upgrade_name = "antimage_mana_void_attack",
		ability_name = "special_upgrade_antimage_mana_void_attack",
		modifier_name = "modifier_antimage_attack_mana_void",
		description = "#special_upgrade_antimage_mana_void_attack",
		value = 11,
		value_text = "11%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "attack_shot",
		values = { chance = 11 },
		target_abilities = { antimage_mana_void = true },
	},
	{
		upgrade_name = "pa_auto_dagger",
		ability_name = "special_upgrade_pa_auto_dagger",
		modifier_name = "modifier_phantom_assassin_auto_dagger_ad_2023",
		description = "#special_upgrade_pa_auto_dagger",
		value = 2.5,
		value_text = "2.5s",
		special_value_name = "cooldown",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "dagger_on_attack",
		values = { cooldown = 2.5 },
		target_abilities = { phantom_assassin_stifling_dagger = true },
	},
	{
		upgrade_name = "marci_unleash_attack",
		ability_name = "special_upgrade_marci_unleash_attack",
		modifier_name = "modifier_marci_unleash_attack_buff_ad_2023",
		description = "#special_upgrade_marci_unleash_attack",
		value = 15,
		value_text = "15%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "fury_unleash",
		values = { chance = 15 },
		target_abilities = { marci_unleash = true },
	},
	{
		upgrade_name = "marci_bodyguard_knockout",
		ability_name = "special_upgrade_marci_bodyguard_knockout",
		modifier_name = "modifier_marci_attack_knockout_sb_2023",
		description = "#special_upgrade_marci_bodyguard_knockout",
		value = 350,
		value_text = "350%",
		special_value_name = "str_mult",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "knockout",
		values = { str_mult = 350, cooldown = 3.0 },
		target_abilities = { marci_bodyguard = true, marci_grapple = true },
		extra_modifiers = { "modifier_marci_attack_knockout_debuff_sb_2023" },
	},
	{
		upgrade_name = "zeus_bolt_counter",
		ability_name = "special_upgrade_zeus_bolt_counter",
		modifier_name = "modifier_zeus_bolt_counter_attack_ad_2023",
		description = "#special_upgrade_zeus_bolt_counter",
		value = 3,
		value_text = "3s",
		special_value_name = "cooldown",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "counter_bolt",
		values = { cooldown = 3.0, radius = 500, aoe_radius = 250 },
		target_abilities = { zuus_lightning_bolt = true },
	},
	{
		upgrade_name = "slark_dark_pact_essence",
		ability_name = "special_upgrade_slark_dark_pact_essence",
		modifier_name = "modifier_slark_dark_pact_essence_bonus_sb_2023",
		description = "#special_upgrade_slark_dark_pact_essence",
		value = 50,
		value_text = "50%",
		special_value_name = "lifesteal",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "essence_shift",
		values = { lifesteal = 50 },
		target_abilities = { slark_dark_pact = true },
	},
	{
		upgrade_name = "mirana_returning_arrow",
		ability_name = "special_upgrade_mirana_returning_arrow",
		modifier_name = "modifier_mirana_returning_arrow_sb_2023",
		description = "#special_upgrade_mirana_returning_arrow",
		value = 1,
		value_text = "Return",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "returning_arrow",
		values = { enabled = 1 },
		target_abilities = { mirana_arrow = true, mirana_arrow_sb_2023 = true },
	},
	{
		upgrade_name = "winter_wyvern_arctic_ally",
		ability_name = "special_upgrade_winter_wyvern_arctic_ally",
		modifier_name = "modifier_winter_wyvern_arctic_burn_friendly_attack_buff",
		description = "#special_upgrade_winter_wyvern_arctic_ally",
		value = 1,
		value_text = "Ally",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "arctic_kiss",
		values = { enabled = 1 },
		target_abilities = { winter_wyvern_arctic_burn = true, winter_wyvern_arctic_burn_sb_2023 = true },
	},
	{
		upgrade_name = "void_spirit_resonant_knockback",
		ability_name = "special_upgrade_void_spirit_resonant_knockback",
		modifier_name = "modifier_void_spirit_resonant_knockback_sb_2023",
		description = "#special_upgrade_void_spirit_resonant_knockback",
		value = 1,
		value_text = "Knockback",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "null_force",
		values = { enabled = 1 },
		target_abilities = { void_spirit_resonant_pulse = true },
	},
	{
		upgrade_name = "gyrocopter_mini_missiles",
		ability_name = "special_upgrade_gyrocopter_mini_missiles",
		modifier_name = "modifier_gyro_extra_mini_missiles_sb_2023",
		description = "#special_upgrade_gyrocopter_mini_missiles",
		value = 1,
		value_text = "Missiles",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "mini_missiles",
		values = { enabled = 1 },
		target_abilities = { gyrocopter_homing_missile = true },
	},
	{
		upgrade_name = "crystal_maiden_snowball",
		ability_name = "special_upgrade_crystal_maiden_snowball",
		modifier_name = "modifier_crystal_maiden_snowball_sb_2023",
		description = "#special_upgrade_crystal_maiden_snowball",
		value = 1,
		value_text = "Snowball",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "snowball",
		values = { enabled = 1 },
		target_abilities = { crystal_maiden_crystal_nova = true, crystal_maiden_frostbite = true },
	},
	{
		upgrade_name = "disruptor_kinetic_field",
		ability_name = "special_upgrade_disruptor_kinetic_field",
		modifier_name = "modifier_disruptor_kinetic_field_heal_dmg_sb_2023",
		description = "#special_upgrade_disruptor_kinetic_field",
		value = 1,
		value_text = "Fence",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "electric_fence",
		values = { enabled = 1 },
		target_abilities = { disruptor_kinetic_field = true },
		extra_modifiers = { "modifier_disruptor_kinetic_field_thinker_sb_2023" },
	},
	{
		upgrade_name = "ursa_overpower_cleave",
		ability_name = "special_upgrade_ursa_overpower_cleave",
		modifier_name = "modifier_ursa_over_power_cleave_sb_2023",
		description = "#special_upgrade_ursa_overpower_cleave",
		value = 65,
		value_text = "65%",
		special_value_name = "outgoing_damage",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "cleave_attack",
		values = { outgoing_damage = 65, lifesteal = 35 },
		target_abilities = { ursa_overpower = true },
	},
	{
		upgrade_name = "razor_static_link_attack",
		ability_name = "special_upgrade_razor_static_link_attack",
		modifier_name = "modifier_razor_static_link_upgrade_sb_2023",
		description = "#special_upgrade_razor_static_link_attack",
		value = 1,
		value_text = "Attack",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "attack_link",
		values = { enabled = 1 },
		target_abilities = { razor_static_link = true },
	},
	{
		upgrade_name = "bane_nightmare_confuse",
		ability_name = "special_upgrade_bane_nightmare_confuse",
		modifier_name = "modifier_bane_nightmare_confused_sb_2023",
		description = "#special_upgrade_bane_nightmare_confuse",
		value = 1,
		value_text = "Confuse",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "confused_enemy",
		values = { enabled = 1 },
		target_abilities = { bane_nightmare = true, bane_nightmare_ad_ranked = true },
	},
	{
		upgrade_name = "juggernaut_blade_fury_pull",
		ability_name = "special_upgrade_juggernaut_blade_fury_pull",
		modifier_name = "modifier_juggernaut_blade_fury_upgrade_sb_2023",
		description = "#special_upgrade_juggernaut_blade_fury_pull",
		value = 1,
		value_text = "Pull",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "fury_force",
		values = { enabled = 1 },
		target_abilities = { juggernaut_blade_fury = true },
		extra_modifiers = { "modifier_juggernaut_blade_fury_thinker_sb_2023", "modifier_juggernaut_blade_fury_pull_sb_2023" },
	},
	{
		upgrade_name = "terrorblade_meta_friends",
		ability_name = "special_upgrade_terrorblade_meta_friends",
		modifier_name = "modifier_terrorblade_meta_friends_sb_2023",
		description = "#special_upgrade_terrorblade_meta_friends",
		value = 1,
		value_text = "Allies",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "friendly_meta",
		values = { enabled = 1 },
		target_abilities = { terrorblade_metamorphosis = true, terrorblade_metamorphosis_aghs2025 = true },
	},
	{
		upgrade_name = "spirit_breaker_auto_charge",
		ability_name = "special_upgrade_spirit_breaker_auto_charge",
		modifier_name = "modifier_spirit_breaker_charge_upgrade_sb_2023",
		description = "#special_upgrade_spirit_breaker_auto_charge",
		value = 1,
		value_text = "Charge",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "auto_charge",
		values = { enabled = 1 },
		target_abilities = { spirit_breaker_charge_of_darkness = true },
		extra_modifiers = { "modifier_spirit_breaker_creep_charging_sb_2023" },
	},
	{
		upgrade_name = "ogre_magi_free_spells",
		ability_name = "special_upgrade_ogre_magi_free_spells",
		modifier_name = "modifier_ogre_magi_free_spells_upgrade_sb_2023",
		description = "#special_upgrade_ogre_magi_free_spells",
		value = 85,
		value_text = "85%",
		special_value_name = "chance",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "infinite_blast",
		values = { chance = 85, radius = 400, dmg_increase_per_cast = 10 },
		target_abilities = { ogre_magi_fireblast = true },
	},
	{
		upgrade_name = "primal_beast_trample_beasts",
		ability_name = "special_upgrade_primal_beast_trample_beasts",
		modifier_name = "modifier_primal_beast_trample_small_beasts_sb_2023",
		description = "#special_upgrade_primal_beast_trample_beasts",
		value = 1,
		value_text = "Beasts",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "baby_beasts",
		values = { enabled = 1 },
		target_abilities = { primal_beast_trample = true },
	},
	{
		upgrade_name = "mars_rebuke_low_hp",
		ability_name = "special_upgrade_mars_rebuke_low_hp",
		modifier_name = "modifier_mars_rebuke_low_hp_sb_2023",
		description = "#special_upgrade_mars_rebuke_low_hp",
		value = 35,
		value_text = "35%",
		special_value_name = "hp_threshold",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "many_rebuke",
		values = { cooldown = 10, heal_pct = 3, hp_threshold = 35 },
		target_abilities = { mars_gods_rebuke = true },
	},
	{
		upgrade_name = "axe_culling_blade_aoe",
		ability_name = "special_upgrade_axe_culling_blade_aoe",
		modifier_name = "modifier_axe_culling_blade_aoe_upgrade_sb_2023",
		description = "#special_upgrade_axe_culling_blade_aoe",
		value = 1,
		value_text = "AOE",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "cull_culling",
		values = { enabled = 1 },
		target_abilities = { axe_culling_blade = true, axe_culling_blade_sb_2023 = true },
	},
	{
		upgrade_name = "ringmaster_impalement_triple",
		ability_name = "special_upgrade_ringmaster_impalement_triple",
		modifier_name = "modifier_ringmaster_impalement_arts_upgrade_sb2023",
		description = "#special_upgrade_ringmaster_impalement_triple",
		value = 3,
		value_text = "3",
		special_value_name = "daggers",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "triple_daggers",
		values = { daggers = 3 },
		target_abilities = { ringmaster_impalement = true },
		extra_modifiers = { "modifier_ringmaster_impalement_arts_max_dmg_sb2023" },
	},
	{
		upgrade_name = "invoker_random_spell_attack",
		ability_name = "special_upgrade_invoker_random_spell_attack",
		modifier_name = "modifier_invoker_random_spell_attack_upgrade_sb2023",
		description = "#special_upgrade_invoker_random_spell_attack",
		value = 1,
		value_text = "Invoke",
		special_value_name = "enabled",
		operator = MINOR_ABILITY_UPGRADE_OP_ADD or 1,
		darkmoon_name = "meteor_upgrade_attack",
		values = { enabled = 1 },
		target_abilities = { invoker_invoke = true },
	},
}

for _, upgrade in ipairs(DARKMOON_SPECIAL_UPGRADE_PORTS) do
	AddDarkmoonUpgrade(upgrade)
end

SPECIAL_UPGRADES.order = {
	"echo_cast",
	"arcane_surge",
	"spell_lifesteal",
	"omnislash_cd",
	"gods_strength_cd",
	"echo_slam",
	"thunder_strike_chance",
	"counter_helix_call",
	"mystic_snake_mana",
	"multishot_chance",
	"cookie_mortimer_kiss",
}

for _, upgrade in ipairs(DARKMOON_SPECIAL_UPGRADE_PORTS) do
	table.insert(SPECIAL_UPGRADES.order, upgrade.upgrade_name)
end

return SPECIAL_UPGRADES
