"Drops" 
{ 
    "npc_dota_alche_greed"
    { 
        "item_book_of_jinada" "100"
        // "item_book_of_cdg" "95"
        "item_book_of_greevil" "75"
        "item_spamp_book" "100"
        "item_attack_range_book" "100"
        "item_mana_regen_book" "100"
        "item_attack_to_barrier" "100"
    }
    "npc_dota_lightning_revenant"
    {
        "item_book_of_multicast" "80"
    }
    "npc_dota_zeus_god"
    {
        "item_book_of_multicast" "80"
    }
    "npc_dota_boss_roshan_beast"
    {
        "item_aegis" "100"
    }
    "npc_dota_boss_tidehunter_ravager"
    {
        "item_book_of_kraken" "80"
    }
}